import { Notify } from 'quasar'
import { api } from 'boot/axios'

export function fetchOptions ({ commit }, payload) {
  api.get('/diccionaris').then(response => {
    commit('setOptions', response.data)
  }).catch(error => {
    console.log(error)
    Notify.create({
      message: error.message
    })
    commit('setOptions', {
      sexe: [{ value: 1, label: '-' }, { value: 2, label: 'Desconegut' }, { value: 3, label: 'Masculí' }, { value: 4, label: 'Femení' }],
      unitatTemps: [{ value: 1, label: '-' }, { value: 2, label: 'Dècada(es)' }, { value: 3, label: 'Any(s)' }, { value: 4, label: 'Mes(os)' }, { value: 5, label: 'Setmana(es)' }, { value: 6, label: 'Dia(es)' }, { value: 7, label: 'Hora(es)' }, { value: 8, label: 'Minut(s)' }, { value: 9, label: 'Segon(s)' }, { value: 10, label: 'Trimestral' }, { value: 11, label: 'Cíclica' }, { value: 12, label: 'Total' }, { value: 13, label: 'CSN' }],
      grupEdat: [{ value: 1, label: '-' }, { value: 2, label: 'Fetus' }, { value: 3, label: 'Recent nascut (0 - 27d)' }, { value: 4, label: 'Lactant (28d - 23m)' }, { value: 5, label: 'Nen (2y - 11y)' }, { value: 6, label: 'Adolescent (12y - 17y)' }, { value: 7, label: 'Adult (18y - 65y)' }, { value: 8, label: 'Ancià (&gt; 65y)' }, { value: 9, label: 'Desconegut' }],
      siNo: [{ value: 1, label: '-' }, { value: 2, label: 'No' }, { value: 3, label: 'Sí' }, { value: 4, label: 'Desconegut' }],
      sospitaRAM: [{ value: 1, label: '-' }, { value: 2, label: 'Sospitós' }, { value: 3, label: 'Concomitant' }, { value: 4, label: 'Interacció' }],
      vacunaNDosi: [{ value: 1, label: '-' }, { value: 2, label: 'Primera dosi' }, { value: 3, label: 'Segona dosi' }, { value: 4, label: 'Tercera dosi' }],
      vacuna: [{ value: 1, label: '-' }, { value: 2, label: 'VAXZEVRIA SUSPENSION INYECTABLE 10 viales multidosis (10 dosis por vial)' }, { value: 3, label: 'SPIKEVAX, DISPERSION INYECTABLE 10 viales (multidosis)' }, { value: 4, label: 'COMIRNATY 30 MICROGRAMOS/DOSIS CONCENTRADO PARA DISPERSIÓN INYECTABLE, 195 viales (multidosis)' }, { value: 5, label: 'COVID-19 VACCINE JANSSEN SUSPENSION INYECTABLE, 10 viales (multidosis)' }, { value: 6, label: 'COMIRNATY 10 MICROGRAMOS/DOSIS CONCENTRADO PARA DISPERSION INYECTABLE, 10 viales multidosis' }, { value: 7, label: 'COMIRNATY 30 MICROGRAMOS/DOSIS DISPERSION INYECTABLE, 10 viales multidosis' }, { value: 8, label: 'COVID-19 VACCINE JANSSEN SUSPENSION INYECTABLE, 20 viales (multidosis)' }, { value: 9, label: 'VAXZEVRIA SUSPENSION INYECTABLE 10 viales multidosis (8 dosis por vial)' }, { value: 10, label: 'Desconeguda' }],
      viaAdmin: [{ value: 1, label: '-' }, { value: 2, label: 'Altra via' }, { value: 3, label: 'Auricular (ótica)' }, { value: 4, label: 'Bucal' }, { value: 5, label: 'Intradèrmica' }, { value: 6, label: 'Intramuscular' }, { value: 7, label: 'Intravenosa bolo' }, { value: 8, label: 'Intravenosa goteig' }, { value: 9, label: 'Intravenosa no especificada' }, { value: 10, label: 'Nasal' }, { value: 11, label: 'Oftàlmica' }, { value: 12, label: 'Oral' }, { value: 13, label: 'Parenteral' }, { value: 14, label: 'Rectal' }, { value: 15, label: 'Respiratoria (inhalació)' }, { value: 16, label: 'Subcutània' }, { value: 17, label: 'Sublingual' }, { value: 18, label: 'Tòpica' }, { value: 19, label: 'Transdèrmica' }, { value: 20, label: 'Transplacentaria' }, { value: 21, label: 'Vaginal' }, { value: 22, label: 'Desconeguda' }, { value: 23, label: 'Inhalada' }, { value: 24, label: 'Intravesical' }, { value: 25, label: 'Venatge oclusiu' }, { value: 26, label: 'Intradiscal (Intraespinal)' }, { value: 27, label: 'Cutània' }, { value: 28, label: 'Intrahepàtica' }, { value: 29, label: 'Dental' }, { value: 30, label: 'Intralesional' }, { value: 31, label: 'Orofaríngea' }, { value: 32, label: 'Intralinfàtica' }, { value: 33, label: 'Endocervical' }, { value: 34, label: 'Intramedular (Médula ósea)' }, { value: 35, label: 'Endosinusal' }, { value: 36, label: 'Intrameningeal' }, { value: 37, label: 'Periarticular' }, { value: 38, label: 'Endotraqueal' }, { value: 39, label: 'Perineural' }, { value: 40, label: 'Epidural' }, { value: 41, label: 'Intraocular' }, { value: 42, label: 'Extra-amniótica' }, { value: 43, label: 'Intrapericardial' }, { value: 44, label: 'Hemodiàlisis' }, { value: 45, label: 'Intraperitoneal' }, { value: 46, label: 'Retrobulbar' }, { value: 47, label: 'Intra cos cavernós' }, { value: 48, label: 'Intrapleural' }, { value: 49, label: 'Subconjuntival' }, { value: 50, label: 'Intra-amniótica' }, { value: 51, label: 'Intrasinovial' }, { value: 52, label: 'Intrarterial' }, { value: 53, label: 'Intratumoral' }, { value: 54, label: 'Subdérmica' }, { value: 55, label: 'Intrarticular' }, { value: 56, label: 'Intratecal' }, { value: 57, label: 'Intrauterí' }, { value: 58, label: 'Intratoràcica' }, { value: 59, label: 'Intracardíaca' }, { value: 60, label: 'Intratraqueal' }, { value: 61, label: 'Intracavernosa' }, { value: 62, label: 'Transmamària' }, { value: 63, label: 'Intracerebral' }, { value: 50, label: 'Intracervical' }, { value: 65, label: 'Uretral' }, { value: 66, label: 'Intracisternal' }, { value: 67, label: 'Intracorneal' }, { value: 68, label: 'Iontoforesis' }, { value: 69, label: 'Intracoronaria' }],
      mesuraPresa: [{ value: 1, label: '-' }, { value: 2, label: 'AD - Augment de la dosi' }, { value: 3, label: 'Desc - Desconeguda' }, { value: 4, label: 'NA - No aplicable' }, { value: 5, label: 'NMD - No es modifica la dosi' }, { value: 6, label: 'RD - Reducció de la dosi' }, { value: 7, label: 'RF - Retirada del fàrmac' }],
      ramMotiva: [{ value: 1, label: '-' }, { value: 2, label: 'Atenció a urgències d\'hospital' }, { value: 3, label: 'Ingrés a l\'hospital' }, { value: 4, label: 'Allargament de l\'hospitalització' }, { value: 5, label: 'Atenció extrahospitalària' }, { value: 6, label: 'Durant l\'hospitalització' }, { value: 7, label: 'Cap de les anteriors o es desconeix' }],
      desen: [{ value: 1, label: '-' }, { value: 2, label: 'Recuperat' }, { value: 3, label: 'En recuperació' }, { value: 4, label: 'No recuperat' }, { value: 5, label: 'Recuperat amb seqüeles' }, { value: 6, label: 'Mortal' }, { value: 7, label: 'Desconegut' }],
      professio: [{ value: 1, label: '-' }, { value: 2, label: '0 Desconegut' }, { value: 3, label: '1 Metge' }, { value: 4, label: '2 Farmacèutic' }, { value: 5, label: '3 Infermer' }, { value: 6, label: '4 Odontòleg' }, { value: 7, label: '5 Altre PS' }, { value: 8, label: '6 Altre professional, en general' }, { value: 9, label: '7 Usuari' }, { value: 10, label: '8 Podòleg' }, { value: 11, label: '9 Fisioterapeuta' }, { value: 12, label: '10 Advocat' }],
      provincia: [{ value: 1, label: '-' }, { value: 2, label: 'Barcelona' }, { value: 3, label: 'Girona' }, { value: 4, label: 'Lleida' }, { value: 5, label: 'Tarragona' }]
    })
  })
}
